version: "3"
services:

#Gateway Service

  # gateway:
  #   depends_on:
  #     - gateway-db
  #   build:
  #     context: ./gateway
  #     dockerfile: Dockerfile
  #   environment:
  #     - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5431/postgres
  #     - SPRING_DATASOURCE_USERNAME=compose-postgres
  #     - SPRING_DATASOURCE_PASSWORD=compose-postgres
  #     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #   ports:
  #     - "8080:8080"
  #   networks:
  #     - my-networks

  #   gateway-db:
  #   image: postgres
  #   environment:
  #     - POSTGRES_USER=compose-postgres
  #     - POSTGRES_PASSWORD=compose-postgres
  #   ports:
  #     - "5431:5431"
  #   networks:
  #     - my-networks  

# Payment Service
  payment-db:
    image: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - PGPORT=5435
    ports:
      - "5435:5435"
    networks:
      - my-networks

  ms-payment:
    depends_on:
      - payment-db
    build:
      context: ./payment
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://payment-db:5435/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - my-networks

 

 # Items Service
  item-db:
    image: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - PGPORT=5433
    ports:
      - "5433:5433"
    networks:
      - my-networks

  ms-item:
    depends_on:
      - item-db
    build:
      context: ./ms-items
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://item-db:5433/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - my-networks 

 

# Shopping Cart Service
  shopping-cart-db:
    image: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - PGPORT=5434
    ports:
      - "5434:5434"
    networks:
      - my-networks 

  ms-shopping-cart:
    depends_on:
      - shopping-cart-db
    build:
      context: ./ms-shopping-cart
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://shopping-cart-db:5434/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    networks:
      - my-networks
   

# Users Service
  user-db:
    image: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
      - PGPORT=5432
    ports:
      - "5432:5432"
    networks:
      - my-networks   

  ms-user-manager:
    depends_on:
      - user-db
    build:
      context: ./ms-user-manager
      dockerfile: Dockerfile
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://user-db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - "8081:8081"
    networks:
      - my-networks



networks:
  my-networks:
    driver: bridge
