version: "3"
services:
  db:
    image: postgres
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    ports:
      - "5432:5432"
    networks:
      - my-networks



networks:
  my-networks:
    driver: bridge